telegram_token:
open_weather_token:

db:
  host:
  database_name:
  user_name:
  user_password:

payment:
  stars_provider_token:
  yookassa_token: "ВАШ_YOOKASSA_TOKEN"
  star_token: "ВАШ_STAR_TOKEN"

logs:
  logs_dir:
  logs_file:
