telegram_token:
open_weather_token:

db:
  host:
  database_name:
  user_name:
  user_password:

logs:
  logs_dir:
  logs_file:

# Настройки донатов
donate:
  # Настройки ЮKassa (получите на kassa.yandex.ru)
  yookassa:
    shop_id: ''  # ваш_shop_id
    secret_key: ''  # ваш_секретный_ключ
  
  # ID администраторов для уведомлений о донатах
  admin_ids:
    - 123456789  # замените на ваш ID Telegram
